[package]
name = "virtual-lb"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
anyhow = "1"
kube = { version = "4.2.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.28", features = ["v1_34", "schemars"] }
futures = "0.3"
thiserror = "2"