apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: virtual-lb
  name: virtual-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-lb
  template:
    metadata:
      labels:
        app: virtual-lb
    spec:
      serviceAccountName: virtual-lb
      containers:
        - image: virtual-lb:latest
          imagePullPolicy: IfNotPresent
          name: virtual-lb
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          ports:
            - name: management
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: management
          readinessProbe:
            httpGet:
              path: /readyz
              port: management
          resources:
            limits:
              memory: 16Mi
            requests:
              memory: 16Mi
              cpu: 100m
