apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtual-lb
resources:
  - ns.yaml
  - permissions.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: virtual-lb
      app.kubernetes.io/instance: virtual-lb
      app.kubernetes.io/component: controller
      app.kubernetes.io/part-of: virtual-lb
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true

images:
  - name: registry.athmer.cloud/virtual-lb
    newTag: latest
