apiVersion: v1
kind: Service
metadata:
  name: virtual
spec:
  loadBalancerClass: "athmer.cloud/virtual"
  selector:
    app: virtual
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
