---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: virtual
  namespace: demo
  annotations:
    athmer.cloud/virtual-lb.name: "demo"
spec:
  loadBalancerClass: "athmer.cloud/virtual"
  selector:
    app: virtual
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
